# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch

  push:
    tags:
      - '*'

jobs:
  Release:
    runs-on: windows-latest
    env:
      #BuildPath: ${{ github.workspace }}\BuildTesting\bin\Release\net5.0-windows
      BuildPath: .
      ZipName: TheThingy

    steps:
      # Build the solution
      - uses: actions/checkout@v2
      - run: echo "Doing stuff on ${{ github.workspace }}"
        
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: 5.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ env.ZipName }}
          path: ${{ github.workspace }}\BuildTesting\bin\Release\net5.0-windows
          
      - name: Download the Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.ZipName }}
          
      - name: Display structure of downloaded files
        run: dir

      # Create a Release on the GitHub project
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name:  ${{ github.ref }}
          draft: false
          prerelease: false

      # Upload the Build Artifact to the Release
      - name: Update release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: .\${{ env.ZipName }}
          asset_name: ${{ env.ZipName }}
          asset_content_type: application/zip

