# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  Build:
    runs-on: windows-latest
    env:
      BuildPath: ${{ github.workspace }}\BuildTesting\bin\Release\net5.0-windows


    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: echo "Doing stuff on ${{ github.workspace }}"
        
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: 5.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: thingy
          path: ${{ github.workspace }}\BuildTesting\bin\Release\net5.0-windows

          retention-days: 1

      - name: Zip Test
        uses: papeloto/action-zip@v1
        with:
          files: ${{ env.BuildPath }}\
          recursive: false
          dest: ${{ github.workspace }}\result.zip

      - name: Upload Zip
        uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: ${{ github.workspace }}\result.zip

    